### ISSUE TITLE
ArgumentError raised when string contains invalid utf8

### ISSUE THREAD

**Issue by aochagavia** [elixir-unicode/unicode_string#3]
I think I have stumbled upon a bug in the library, though I am not totally sure because there might be some unicode complexities I am unaware of. Btw thanks for putting the library together. Even without support for strings with invalid utf8, it will be quite useful!

### Instructions to reproduce

Function call: `Unicode.String.next("this string contains invalid utf8" <> <<240>>, break: :word)`

Expected output: `this`

Actual output:

```
** (ArgumentError) argument error
    (stdlib 4.1) re.erl:788: :re.run(<<104, 105, 115, 32, 115, 116, 114, 105, 110, 103, 32, 99, 111, 110, 116, 97, 105, 110, 115, 32, 105, 110, 118, 97, 108, 105, 100, 32, 117, 116, 102, 56, 240>>, {:re_pattern, 1, 1, 0, <<69, 82, 67, 80, 134, 0, 0, 0, 60, 8, 0, 33, 1, 8, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, [:global, {:capture, :first}])
    (elixir 1.13.4) lib/regex.ex:481: Regex.safe_run/3
    (elixir 1.13.4) lib/regex.ex:550: Regex.split/3
    (unicode_string 1.1.0) lib/unicode/segment.ex:204: Unicode.String.Segment.evaluate_rule/2
    (unicode_string 1.1.0) lib/unicode/segment.ex:169: anonymous fn/3 in Unicode.String.Segment.evaluate_rules/2
    (elixir 1.13.4) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.4) lib/enum.ex:2442: Enum.reduce_while/3
    (unicode_string 1.1.0) lib/unicode/segment.ex:167: Unicode.String.Segment.evaluate_rules/2
    (unicode_string 1.1.0) lib/unicode/break.ex:118: Unicode.String.Break.next_at/4
    (unicode_string 1.1.0) lib/unicode/break.ex:92: Unicode.String.Break.next/4
```

### Considerations / questions

I would assume that it is not necessary to scan the whole string in order to be able to get the next word.

**Comment by kipcole9** [comment]
@aochagavia thanks for raising the issue.  The contract for `Unicode.String.next/2` is for the string to be valid unicode. Validating unicode isn't a zero-cost activity (the whole string has to be processed) so there is no validation checking in the `:unicode_string` library.

You might reasonably think it should be fine when just looking for the next break.  However the underlying break algorithm is `regex` driven (you can see the rules [here](https://github.com/elixir-unicode/unicode_string/tree/master/priv/segments)). And is appears that the erlang `:re` module does require valid unicode for the string.

Net result is that supporting invalid unicode is out of scope of the library and not practically solvable due to `:re`'s intolerance for invalid unicode strings.
